### ISSUE TITLE
Complete IPR - Executive Summary, etc.

### ISSUE THREAD

**Issue by rhefner1** [cookomatic/cookomatic-docs#2]

**Comment by rhefner1** [comment]
Put business plan

**Comment by rhefner1** [comment]
**From Dr. Sturgill**: For user tests, put intro at beginning of section and put vague description

**Comment by amham17** [comment]
@rhefner1  Add notes/fill out the design section of the IPR.

**Comment by amham17** [comment]
Left to complete:
Executive Summary - @amham
Requirements (Constraints) - amham
Preliminary Design - @rhefner1 
Preliminary Test Plan and Results - amham
